bic-org-uk/bic-lcf

lcf-schema/src/main/resources/lcf-v1.0-entities.xsd

... allowing them to be omitted at the point of creation.

Made the references to element "identifier" optional

---

lcf-schema/src/main/resources/lcf-v1.0-entities.xsd

Change of chargeStatus base type as per issue #16

Change of chargeStatus base type from xs:token to xs:string

---

lcf-schema/src/main/resources/lcf-v1.0-entities.xsd

Add additional CMT code list entries as per issue #34

Add additional entries to the CMT code list enumeration (issue #34)

---

lcf-schema/src/main/resources/lcf-v1.0-rest-responses.xsd

Remove lcf-reservation-response as per issue #32

Remove lcf-reservation-response as per issue #32

---

lcf-schema/src/main/resources/lcf-v1.0-entities.xsd

Add following fields to patron entity as per issue #41:
* barcode-id
* additional-patron-id
* patron-category
* patron-tag
* patron-expiration-date
* deposit-balance

Add fields to patron entity as per issue #41

---

lcf-schema/src/main/resources/lcf-v1.0-entities.xsd

Add missing target namespace as described in issue #48

Add target namespace (http://ns.bic.org.uk/lcf/1.0) to entities schema

---

lcf-schema/src/main/resources/lcf-v1.0-entities.xsd

XML Schema change as defined in #57

Make charge-ref in Payment (E08D05) non mandatory

---

.gitignore
lcf-schema/src/main/resources/lcf-v1.0-entities.xsd

XML Schema change as defined in #53

Add hold-queue-position to Reservation entity (E06D15)

---

.gitignore
lcf-schema/src/main/resources/lcf-v1.0-entities.xsd

Add authorisation entity as per issue #55

Add authorisation entity as per issue #55

---

.gitignore
lcf-schema/src/main/resources/lcf-v1.0-entities.xsd

Added MES05 to mediaTypeScheme as per issue #70

Added MES05 to mediaTypeScheme as per issue #70

---

lcf-schema/src/main/resources/lcf-v1.0-entities.xsd

Added CHT14 to chargeType as per issue #71

Added CHT14 to chargeType as per issue #71

---

lcf-schema/src/main/resources/lcf-v1.0-entities.xsd

Miscellaneous Schema Bugs

---

lcf-schema/src/main/resources/lcf-v1.0-entities.xsd

Add associated-patron-group to patron entity

---

lcf-schema/src/main/resources/lcf-v1.0-entities.xsd

Add PAY (AUT02) to Authorisation code list

---

lcf-schema/src/main/resources/lcf-v1.0-entities.xsd

Updated Location entity

---

lcf-schema/src/main/resources/lcf-v1.0-entities.xsd
lcf-schema/src/main/resources/lcf-v1.0-rest-responses.xsd

Add Notification Mechanism

---

lcf-schema/src/main/resources/lcf-v1.0-entities.xsd

Entity Notes should be repeatable in all cases

---

lcf-schema/src/main/resources/lcf-v1.0-entities.xsd

Authority ID

---

README.md
docs/LCF-AuthenticationAuthorisation.md
docs/LCF-CodeLists.md
docs/LCF-DataFrameworks.md
docs/LCF-ImplementationProfiles.md
docs/LCF-InformationEntityXMLBindings.md
docs/LCF-RESTWebServiceSpecification.md
docs/_config.yml
docs/index.md

Add github pages frontmatter
Fix title\version boilerplate
Fix markdown
Fix links
Update README.md
Update _config.yml

Convert wiki to github pages

---

docs/LCF-AuthenticationAuthorisation.md
docs/LCF-CodeLists.md
docs/LCF-DataFrameworks.md
docs/LCF-ImplementationProfiles.md
docs/LCF-InformationEntityXMLBindings.md
docs/LCF-RESTWebServiceSpecification.md
docs/index.md
lcf-schema/pom.xml

Version number checks
See checklist table in wiki: https://github.com/bic-org-uk/bic-lcf/wiki/Editorial-Guidelines-(git-workflow)#version-release-checklist

Preparing for release v1.0.1

---

docs/LCF-AuthenticationAuthorisation.md
docs/LCF-CodeLists.md
docs/LCF-DataFrameworks.md
docs/LCF-ImplementationProfiles.md
docs/LCF-InformationEntityXMLBindings.md
docs/LCF-RESTWebServiceSpecification.md
docs/_config.yml
docs/index.md
lcf-schema/pom.xml
lcf-schema/src/main/resources/lcf-v1.0-codelists.xsd

Update version ready for next release as per checklist
https://github.com/bic-org-uk/bic-lcf/wiki/Editorial-Guidelines-(git-workflow)#version-release-checklist

Update version for next release

---

docs/LCF-DataFrameworks.md

Changed 'LCF-CodeLists#' to 'LCF-CodeLists.md#'.

Fix links to code lists

---

docs/LCF-CodeLists.md

Code value 'ACC' added to code list AUT

---

README.md
docs/LCF-AuthenticationAuthorisation.md
docs/LCF-CodeLists.md
docs/LCF-DataFrameworks.md
docs/LCF-ImplementationProfiles.md
docs/LCF-InformationEntityXMLBindings.md
docs/LCF-RESTWebServiceSpecification.md
docs/_config.yml
docs/index.md
lcf-schema/pom.xml
lcf-schema/src/main/resources/lcf-v1.0-codelists.xsd
lcf-schema/src/main/resources/lcf-v1.0-entities.xsd
lcf-schema/src/main/resources/lcf-v1.0-onix-codelists.xsd
lcf-schema/src/main/resources/lcf-v1.0-rest-responses.xsd

This is to make sure master and develop branches are in sync before working on the next version of LCF

Releasing v1.1.0

---

docs/LCF-CodeLists.md
docs/LCF-DataFrameworks.md
docs/LCF-ImplementationProfiles.md
docs/LCF-InformationEntityXMLBindings.md
docs/LCF-RESTWebServiceSpecification.md
docs/_config.yml
docs/index.md

Set release date to 23 December 2019.

Releasing v1.2.0

---

lcf-schema/pom.xml

I should have checked the Wiki editorial list...

Editorial patches for v1.2.0 release

---

docs/LCF-InformationEntityXMLBindings.md

Further patch of master for LCF v1.2.0
